---
#HackerU ansible task 1
- name: Set Moscow timezone
  ansible.builtin.command: timedatectl set-timezone Europe/Moscow


#HackerU ansible task 2
- name: Time synchronisation
  block:
    - name: Install chrony Debian-like
      apt:
        name: chrony
        state: present
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install chrony CentOS
      yum:
        name: chrony
        state: present
        update_cache: yes
      when: ansible_distribution == 'CentOS'

    - name: Set additional time servers
      blockinfile:
        path: '{{ chrony_path }}'
        block: |
          server  time-a-g.nist.gov
          server  129.6.15.29

    - name: Enable and restart chrony
      systemd:
        name: '{{ chrony_name }}'
        enabled: yes
        daemon_reload: yes
        state: restarted


#HackerU ansible task 3
- name: Bruteforce defenсе
  block:
    - name: Install fail2ban
      package:
        name: fail2ban
        state: present

    - name: Enable and restart fail2ban
      systemd:
        name: fail2ban
        enabled: yes
        daemon_reload: yes
        state: restarted

#HackerU ansible task 4
- name: SSHd configuration
  block:
    - name: Copy config file
      copy:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
        backup: yes

    - name: Restart service
      systemd:
        name: sshd
        enabled: yes
        daemon_reload: yes
        state: restarted
  tags: sshd

#HackerU ansible task 5
- name: Disabling and stop autofs
  systemd:
    name: autofs
    enabled: no
    state: stopped
