#Lists of VMs settings
servers=[
  {
    :hostname => "debian",
    :ip => "192.168.56.1",
    :box => "debian/buster64"
  },
  {
    :hostname => "centos",
    :ip => "192.168.56.2",
    :box => "centos/7"
  }
]

Vagrant.configure("2") do |config|
  config.vm.base_mac = nil
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
    vb.linked_clone = true
  end
#Use array server section
  servers.each do |machine|
    config.vm.define machine[:hostname] do |n|
      n.vm.hostname = machine[:hostname]
      n.vm.network "private_network", ip: machine[:ip]
      n.vm.box = machine[:box]
    end
  end
end

#      if machine_id == N
#        n.vm.provision :ansible do |ansible|
#          ansible.limit = "all"
#          ansible.playbook = "site.yaml"
#          ansible.raw_arguments = [ "-D"]
#        end
#      end
#    end
#  end
#end
