---
- name: test message
  debug:
    msg: "it works"

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: debug-shell
    state: stopped
    enabled: no

- name: Disable ctrl-alt-del
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/systemd/system/ctrl-alt-del.target
    state: link

- name: Disable Ctrl-Alt-Del Burst Action
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    line: CtrlAltDelBurstAction=none
    create: yes

- name: Disable Ctrl-Alt-Del Burst Action
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    line: CREATE_HOME yes
    create: yes

- name: Verify passwd
  ansible.builtin.shell: |
    awk -F: '$2!="x"' /etc/passwd

