---
#HackerU ansible task 0
- name: Preparing all
  hosts: all
  gather_facts: no
  roles:
    - generic

#HackerU ansible task 1-
- name: Security hardening linux servers
  hosts: lab4
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
  - "vars/common.yml"
  - [ "vars/{{ ansible_facts['os_family'] }}.yml", "vars/os_defaults.yml" ]

  roles:
    - bulletproof
